export const houses = [
  {
    id: 1,
    img: [
      "/mock/house/1/1.jpg",
      "/mock/house/1/2.jpg",
      "/mock/house/1/3.jpg",
      "/mock/house/1/4.jpg",
      "/mock/house/1/5.jpg",
    ],
    rate: "4.29",
    locate: "대구광역시 동구 율하동",
    price: "160",
    person: 8,
  },
  {
    id: 2,
    img: [
      "/mock/house/2/1.jpg",
      "/mock/house/2/2.jpg",
      "/mock/house/2/3.jpg",
      "/mock/house/2/4.jpg",
      "/mock/house/2/5.jpg",
    ],
    rate: "4.21",
    locate: "대구광역시 달서구 두류동",
    price: "110",
    person: 2,
  },
  {
    id: 3,
    img: [
      "/mock/house/3/1.jpg",
      "/mock/house/3/2.jpg",
      "/mock/house/3/3.jpg",
      "/mock/house/3/4.jpg",
      "/mock/house/3/5.jpg",
    ],
    rate: "4.35",
    locate: "대구광역시 수성구 범어동",
    price: "100",
    person: 8,
  },
  {
    id: 4,
    img: [
      "/mock/house/4/1.jpg",
      "/mock/house/4/2.jpg",
      "/mock/house/4/3.jpg",
      "/mock/house/4/4.jpg",
      "/mock/house/4/5.jpg",
    ],
    rate: "3.81",
    locate: "대구광역시 북구 노원동1가",
    price: "50",
    person: 5,
  },
  {
    id: 5,
    img: [
      "/mock/house/5/1.jpg",
      "/mock/house/5/2.jpg",
      "/mock/house/5/3.jpg",
      "/mock/house/5/4.jpg",
      "/mock/house/5/5.jpg",
    ],
    rate: "3.89",
    locate: "대구광역시 북구 산격동",
    price: "70",
    person: 5,
  },
  {
    id: 6,
    img: [
      "/mock/house/6/1.jpg",
      "/mock/house/6/2.jpg",
      "/mock/house/6/3.jpg",
      "/mock/house/6/4.jpg",
      "/mock/house/6/5.jpg",
    ],
    rate: "4.45",
    locate: "대구광역시 수성구 수성동2가",
    price: "160",
    person: 1,
  },
  {
    id: 7,
    img: [
      "/mock/house/7/1.jpg",
      "/mock/house/7/2.jpg",
      "/mock/house/7/3.jpg",
      "/mock/house/7/4.jpg",
      "/mock/house/7/5.jpg",
    ],
    rate: "3.87",
    locate: "대구광역시 남구 이천동",
    price: "90",
    person: 7,
  },
  {
    id: 8,
    img: [
      "/mock/house/8/1.jpg",
      "/mock/house/8/2.jpg",
      "/mock/house/8/3.jpg",
      "/mock/house/8/4.jpg",
      "/mock/house/8/5.jpg",
    ],
    rate: "3.82",
    locate: "대구광역시 동구 서호동",
    price: "80",
    person: 2,
  },
  {
    id: 9,
    img: [
      "/mock/house/9/1.jpg",
      "/mock/house/9/2.jpg",
      "/mock/house/9/3.jpg",
      "/mock/house/9/4.jpg",
      "/mock/house/9/5.jpg",
    ],
    rate: "3.98",
    locate: "대구광역시 중구 달성동",
    price: "120",
    person: 8,
  },
  {
    id: 10,
    img: [
      "/mock/house/10/1.jpg",
      "/mock/house/10/2.jpg",
      "/mock/house/10/3.jpg",
      "/mock/house/10/4.jpg",
      "/mock/house/10/5.jpg",
    ],
    rate: "3.89",
    locate: "대구광역시 달서구 두류동",
    price: "170",
    person: 6,
  },
  {
    id: 11,
    img: [

      "/mock/house/11/1.jpg",
      "/mock/house/11/2.jpg",
      "/mock/house/11/3.jpg",
      "/mock/house/11/4.jpg",
      "/mock/house/11/5.jpg",
    ],
    rate: "4.11",
    locate: "경상북도 경산시 조영동",
    price: "190",
    person: 8,
  },
  {
    id: 12,
    img: [
      "/mock/house/12/1.jpg",
      "/mock/house/12/2.jpg",
      "/mock/house/12/3.jpg",
      "/mock/house/12/4.jpg",
      "/mock/house/12/5.jpg",
    ],
    rate: "3.92",
    locate: "경상북도 경산시 중방동",
    price: "140",
    person: 2,
  },
];
