export const memberList = [
  {
    index: 0,
    id: "member0",
    password: "member0",
    name: "노재진",
    nickname: "맘모스",
    profileImage: '/mock/member/member0.jpg',
  },
  {
    index: 1,
    id: "member1",
    password: "member1",
    name: "고민혜",
    nickname: "불가사리",
    profileImage: '/mock/member/member1.jpg',
  },
  {
    index: 2,
    id: "member2",
    password: "member2",
    name: "조다영",
    nickname: "얼룩상어",
    profileImage: '/mock/member/member2.jpg',
  },
  {
    index: 3,
    id: "member3",
    password: "member3",
    name: "임유현",
    nickname: "바다사자",
    profileImage: '/mock/member/member3.jpg',
  },
  {
    index: 4,
    id: "member4",
    password: "member4",
    name: "최원준",
    nickname: "버들붕어",
    profileImage: '/mock/member/member4.jpg',
  },
  {
    index: 5,
    id: "member5",
    password: "member5",
    name: "김정민",
    nickname: "까마귀",
    profileImage: '/mock/member/member5.jpg',
  },
];